### ISSUE TITLE
Great new name! @JuliaClimate or @JuliaOcean?

### ISSUE THREAD

**Issue by gaelforget** [milankl/ShallowWaters.jl#124]
Hi @milankl 

Love the new name! 🎉 w.r.t pkg registration too 😃 

The new name made me wonder, though, whether @JuliaOcean could be an even better home for this package than @JuliaClimate 

What you think?

ps. more on @JuliaOcean next week... Seems timely now that the scope discussion on @JuliaClimate is well engaged & in preparation for [this OSM20 workshop](https://agu.confex.com/agu/osm20/meetingapp.cgi/Session/92105). I waited a bit to avoid messing with the @JuliaClimate discussion by immediately bringing up @JuliaOcean 

pps. in any event, if you'd like, I would suggest advertising this @ the [OSM20 workshop](https://agu.confex.com/agu/osm20/meetingapp.cgi/Session/92105). I am guessing that you are not flying to San Diego, are you? I hope we will be able to broadcast & record...

**Comment by milankl** [comment]
Hey Gael!

I thought the idea of @JuliaClimate was to basically cover @JuliaOcean too. I honestly don't mind that much, but like to idea of having a wider scope than what "Ocean" seems to aim for.

Great that you organise a OSM workshop, no, unfortunately I'm not going this year. And yes, feel free to advertise this! You can find some videos [here](https://www.milank.de/videos), let me know if you need anything else, and send me the link if there's some live streaming or recording!
