### ISSUE TITLE
demo example request 

### ISSUE THREAD

**Issue by hafez-ahmad** [milankl/ShallowWaters.jl#140]
this is great work. would you please add some example/demo how to run or manipulate the output?

**Comment by milankl** [comment]
You can find a quick example in the readme. If you require more specific explanations, please ask. The data is output as netcdf file. You can use any netcdf library to read & analyse the data. In Julia there is [NetCDF.jl](https://github.com/JuliaGeo/NetCDF.jl), [NCDatasets.jl](https://github.com/Alexander-Barth/NCDatasets.jl), popular for the shell are also ncdump, [ncview](http://meteora.ucsd.edu/~pierce/ncview_home_page.html), [cdo](https://code.mpimet.mpg.de/projects/cdo) and many more

**Comment by hafez-ahmad** [comment]
thank you for making great Julia ShallowWaters package. would you add some examples of how we model wave model and ocean current model using this?

**Comment by milankl** [comment]
You can for example run a double gyre simulation like this
```julia
julia> using ShallowWaters
julia> P = RunModel(Ndays=100,nx=100,L_ratio=1,bc="nonperiodic",wind_forcing_x="double_gyre",topography="seamount");
Starting ShallowWaters on Sat, 15 Aug 2020 11:59:21 without output.
100% Integration done in 13.7s.
```
Sea surface height can be visualised via
```julia
julia> using PyPlot
julia> pcolormesh(P.η')
```
![Figure_1](https://user-images.githubusercontent.com/25530332/90311163-1ee40a00-def0-11ea-8911-810d7762cd3f.png)
Or let's calculate the speed of the currents
```julia
julia> speed = sqrt.(Ix(P.u.^2)[:,2:end-1] + Iy(P.v.^2)[2:end-1,:])
```
`P.u` and `P.v` are the u,v velocity components on the Arakawa C-grid. To add them, we need to interpolate them with `Ix,Iy` (which are exported too), then chopping off the edges to get two arrays of the same size.
```julia
julia> pcolormesh(speed')
```
![Figure_2](https://user-images.githubusercontent.com/25530332/90311211-88fcaf00-def0-11ea-8308-b4f438495152.png)
Such that the currents are strongest around the two eddies, as expected in this quasi-geostrophic setup.

**Comment by milankl** [comment]
This example was added to the README.md

**Comment by hafez-ahmad** [comment]
Thank you so much.highly appreciated your effort.
