### ISSUE TITLE
Typos in readme

### ISSUE THREAD

**Issue by tmigot** [milankl/ShallowWaters.jl#162]
![image_2022-01-18_101045](https://user-images.githubusercontent.com/25304288/149963795-76112048-e15c-40bd-ae0e-788950abcff3.png)

The equations in the readme are filled with `u⃗⋅∇`
I am wondering if this is the expected behavior.

**Comment by milankl** [comment]
Thanks for pointint this out, it seems to be a browser issue on your side as they are even correctly rendered for me in this post
![image](https://user-images.githubusercontent.com/25530332/149964608-66a0e1c8-fe08-49bc-825a-e97315d2247d.png)

Technically, we should move this description into a proper documentation with latex support. But I'm afraid, I currently don't have the capacities to do so.

**Comment by tmigot** [comment]
Oh, I see. If you by "proper documentation with latex support", you mean documentation using https://github.com/JuliaDocs/Documenter.jl and Github-pages, I have some experience with it and can open a PR.

**Comment by milankl** [comment]
That contribution would be awesome! Happy to review any PR, just currently don't have the time to lead on this myself. Many functions have some brief doc string, but there's obviously much more documentation need... Sorry for never having completed this project with a fully consistent documentation!
